#!/bin/bash

#****************************************************************************************************#
#                                        AUTO-BACKUP-FAILOVER                                        #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# SCRIPT MADE TO RUN BY CRON EVERY MINUTE                                                            #
#----------------------------------------------------------------------------------------------------#

if (($EUID!=0))
then
  echo "You must be root to run this script" 2>&1
  exit 1
fi

#----------------------------------------------------------------------------------------------------#
# CONFIGURATION VARIABLES                                                                            #
#----------------------------------------------------------------------------------------------------#

create_dir="/root/remblock/backup-failover"
config_file="/root/remblock/backup-failover/config"
backup_failover_script_path="/root/remblock/backup-failover/bp-failover"
#PATH to used commands
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
cron_cmd="/root/remblock/backup-failover/backup-failover"
now_epoch="$(date +%s)"

#----------------------------------------------------------------------------------------------------#
# CREATE DIRECTORY IF IT DOESN'T EXIST                                                               #
#----------------------------------------------------------------------------------------------------#

if [ ! -d "$create_dir" ]
then
  mkdir -p "$create_dir"
  cp -p "$0" "$create_dir"
fi

#----------------------------------------------------------------------------------------------------#
# CREATE CONFIG FILE IF IT DOESN'T EXIST                                                             #
#----------------------------------------------------------------------------------------------------#

if [ ! -f "$config_file" ]
then
  echo "#Configuration file for the failover script" > "$config_file"
  echo "#Make the entries as variable=value" >> "$config_file"
  echo " " >> "$config_file"
fi

#----------------------------------------------------------------------------------------------------#
# INSTALL CRONTAB LINE IF IT DOESN'T EXIST                                                           #
#----------------------------------------------------------------------------------------------------#

if [ ! -z "$cron_cmd" ] && ! crontab -u root -l | grep -v '^ *#' | grep "$cron_cmd" &>/dev/null
then
  (crontab -u root -l ; echo "*/1 * * * * $cron_cmd") | crontab -u root -
fi

#----------------------------------------------------------------------------------------------------#
# RETRIEVE YES OR NO ANSWER FROM THE USER                                                            #
#----------------------------------------------------------------------------------------------------#

function get_user_answer_yn(){
  while :
  do
    read -p "$1 [y/n]: " answer
    answer="$(echo $answer | tr '[:upper:]' '[:lower:]')"
    case "$answer" in
      yes|y) return 0 ;;
      no|n) return 1 ;;
      *) echo  "Invalid Answer [yes/y/no/n expected]";continue;;
    esac
  done
}

#----------------------------------------------------------------------------------------------------#
# RETRIEVE VALUE FROM THE CONFIG FILE, RETURN IT WITH THE VARIABLE "global_value"                    #
#----------------------------------------------------------------------------------------------------#

function get_config_value() {
  global_value=$(grep -v '^#' "$config_file" | grep "^$1=" | awk -F '=' '{print $2}')
  if [ -z "$global_value" ]
  then
    return 1
  else
    return 0
  fi
}

#****************************************************************************************************#
#                                   GETTING POSSIBLE MISSING VALUE                                   #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# RETRIEVE PRODUCER NAME IF NOT ALREADY SET IN THE CONFIG FILE                                       #
#----------------------------------------------------------------------------------------------------#

if get_config_value accountname
then
  accountname="$global_value"
elif [ -z "$global_value" ]
then
  accountname=$(cat config/config.ini | grep 'producer-name' | awk '{print $3}')
  if [ -z "$accountname" ]
  then
    echo ""
    read -p "ENTER YOUR PRODUCER NAME: " -e accountname
  fi  
  echo "accountname=$accountname" >> "$config_file"
fi

#----------------------------------------------------------------------------------------------------#
# RETRIEVE WALLET PASSWORD IF NOT ALREADY SET IN THE CONFIG FILE                                     #
#----------------------------------------------------------------------------------------------------#

if get_config_value walletpass
then
  walletpass="$global_value"
elif [ -z "$global_value" ]
then
  walletpass=$(cat walletpass)
  if [ -z "$walletpass" ]
  then
    echo ""
    read -p "ENTER YOUR WALLET PASSWORD: " -e walletpass
  fi
  echo "walletpass=$walletpass" >> "$config_file"
fi

#----------------------------------------------------------------------------------------------------#
# RETRIEVE ACTIVE PRODUCER PUBLIC KEY IF NOT ALREADY SET IN THE CONFIG FILE                          #
#----------------------------------------------------------------------------------------------------#

if get_config_value activeproducerpublickey
then
  activeproducerpublickey="$global_value"
elif [ -z "$global_value" ]
then
  activeproducerpublickey=$(remcli -u https://remchain.remme.io get table rem rem producers -L $accountname -U $accountname | grep 'producer_key' | awk '{print $2}' | tr -d '"' | tr -d ',')
  if [ -z "$activeproducerpublickey" ]
  then
    echo ""
    read -p "ENTER YOUR PRODUCER PUBLIC KEY: " -e activeproducerpublickey
  fi
  echo "activeproducerpublickey=$activeproducerpublickey" >> "$config_file"
fi

#----------------------------------------------------------------------------------------------------#
# RETRIEVE PERMISSION IF NOT ALREADY SET IN THE CONFIG FILE                                          #
#----------------------------------------------------------------------------------------------------#

if get_config_value producerpermission
then
  producerpermission="$global_value"
elif [ -z "$global_value" ]
then
  producerpermission=$(remcli -u https://remchain.remme.io get account $accountname | grep $activeproducerpublickey | awk '{print $1}' | sed -n 1p)
  if [ -z "$producerpermission" ]
  then
    echo ""
    read -p "ENTER YOUR PRODUCER PERMISSION: " -e producerpermission
  fi
  echo "producerpermission=$producerpermission" >> "$config_file"
fi

#----------------------------------------------------------------------------------------------------#
# RETRIEVE CONFIG PRODUCER PUBLIC KEY IF NOT ALREADY SET IN THE CONFIG FILE                          #
#----------------------------------------------------------------------------------------------------#

if get_config_value configproducerpublickey
then
  configproducerpublickey="$global_value"
elif [ -z "$global_value" ]
then
  configproducerpublickey=$(cat config/config.ini | grep 'signature-provider' | awk '{print $3}' | sed 's/=.*//')
  echo "configproducerpublickey=$configproducerpublickey" >> "$config_file"
  echo ""
fi

#----------------------------------------------------------------------------------------------------#
# GET TELEGRAM DATA IF NOT ALREADY ON THE CONFIG FILE                                                #
#----------------------------------------------------------------------------------------------------#

if get_config_value telegram_enabled
then
  if [ "$global_value" = "true" ]
  then
    telegram_enabled=true
  else
    telegram_enabled=false
  fi
else
  echo ""
  if get_user_answer_yn "ENABLE TELEGRAM NOTIFICATIONS"
  then
    telegram_enabled=true
    echo "telegram_enabled=true" >> "$config_file"
  else
    telegram_enabled=false
    echo "telegram_enabled=false" >> "$config_file"
  fi
fi
if $telegram_enabled
then
  if get_config_value telegram_token
  then
    telegram_token="$global_value"
  elif [ -z "$global_value" ]
  then
    echo ""
    read -p "ENTER YOUR TELEGRAM TOKEN API: " -e telegram_token
    echo "telegram_token=$telegram_token" >> "$config_file"
  fi
  if get_config_value telegram_chatid
  then
    telegram_chatid="$global_value"
  elif [ -z "$global_value" ]
  then
    echo ""
    read -p "ENTER YOUR TELEGRAM CHAT ID: " -e telegram_chatid
    echo "telegram_chatid=$telegram_chatid" >> "$config_file"
  fi
fi

#----------------------------------------------------------------------------------------------------#
# USER BLOCK MINUTE VALUE IF NOT SET IN THE CONFIG FILE                                              #
#----------------------------------------------------------------------------------------------------#

if get_config_value check_last_block_minutes
then
  check_last_block_minutes="$global_value"
elif [ -z "$global_value" ]
then
  echo ""
  read -p "ENTER MINTUES TO AUTO-FAILOVER IF YOU'RE NOT PRODUCING?: " -e check_last_block_minutes
  echo ""
  echo "check_last_block_minutes=$check_last_block_minutes" >> "$config_file"
fi

#----------------------------------------------------------------------------------------------------#
# USER HEAD BLOCK MINUTE VALUE IF NOT ALREADY SET IN THE CONFIG FILE                                 #
#----------------------------------------------------------------------------------------------------#

if get_config_value check_last_head_block_minutes
then
  check_last_head_block_minutes="$global_value"
elif [ -z "$global_value" ]
then
  check_last_head_block_minutes=5
  echo "check_last_head_block_minutes=$check_last_head_block_minutes" >> "$config_file"
fi

#----------------------------------------------------------------------------------------------------#
# CREATE THE BACKUP FAILOVER SCRIPT IF IT DOESN' EXIST                                               #
#----------------------------------------------------------------------------------------------------#

if [ ! -f "$backup_failover_script_path" ]
then
cat > "$backup_failover_script_path" << 'DOC'
#!/usr/bin/env bash

#----------------------------------------------------------------------------------------------------#
# REGISTER AGAIN AS A BLOCK PRODUCER USING YOUR BACKUP KEYS                                          #
#----------------------------------------------------------------------------------------------------#

remcli wallet unlock --password $walletpass > /dev/null 2>&1
output=$(remcli -u https://remchain.remme.io system regproducer $accountname $configproducerpublickey -x 120 -p $accountname@$producerpermission)
sudo remnode --config-dir ./config/ --data-dir ./data/ --fix-reversible-blocks --force-all-checks

DOC
  chmod u+x "$backup_failover_script_path"
fi

#****************************************************************************************************#
#                                       FUNCTIONS DEFINITIONS                                        #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# SET TELEGRAM SEND COMMAND TO FALSE                                                                 #
#----------------------------------------------------------------------------------------------------#

send_message=false

#----------------------------------------------------------------------------------------------------#
# TRANSLATE THE TIME FORMAT FROM REMCLI FORMATE TO EPOCH TIME                                        #
#----------------------------------------------------------------------------------------------------#

function remnodelogtime_to_epoch() {
  temp_date="$( echo $1 | awk -F '.' '{ print $1}' | tr '-' '/' | tr 'T' ' ')"
  echo $(date "+%s" -d "$temp_date")
}

#----------------------------------------------------------------------------------------------------#
# FUNCTION THAT CHECKS WHETHER THE NODE HAS ACTUAL PRODUCED A BLOCK WITHIN THE SET MINUTES           #
#----------------------------------------------------------------------------------------------------#

function check_produce_minutes() {
  active=$(remcli -u https://remchain.remme.io get table rem rem producers -L $accountname -U $accountname | grep 'is_active' | awk '{print $2}' | tr -d '"' | tr -d ',') 
  if [ -z "$active" ]
  then
    active=$(remcli get table rem rem producers -L $accountname -U $accountname | grep 'is_active' | awk '{print $2}' | tr -d '"' | tr -d ',')
  fi
  if ! pgrep 'bp-failover' &> /dev/null
  then
    #Execute failover only if it's registered
    if [ "$active" == "1" ]
    then
      export accountname
      export walletpass
      export producerpermission
      export producerpublickey
      bash "$backup_failover_script_path" &>/dev/null
      telegram_message="Auto-Backup-Failover script has executed"
      send_message=true
    fi
  fi
}

#----------------------------------------------------------------------------------------------------#
# MAIN PART OF THE SCRIPT                                                                            #
#----------------------------------------------------------------------------------------------------#

if [ ! -f "/root/check_backup_failover" ]
then
  cat << EOF > "/root/check_backup_failover" 
true
EOF
else
  if grep "true" "check_backup_failover"
  then
    last_block_date=$(remcli -u https://remchain.remme.io get table rem rem producers -L $accountname -U $accountname | grep 'last_block_time' | awk '{print $2}' | tr -d '"' | tr -d ',')
    if [ -z "$last_block_date" ]
    then
      last_block_date=$(remcli get table rem rem producers -L $accountname -U $accountname | grep 'last_block_time' | awk '{print $2}' | tr -d '"' | tr -d ',')
    fi
    last_block_epoch=$(remnodelogtime_to_epoch "$last_block_date")
    last_head_block_date=$(remcli get info | grep 'head_block_time' | awk '{print $2}' | tr -d '"' | tr -d ',')
    last_head_block_epoch=$(remnodelogtime_to_epoch "$last_head_block_date")
    last_block_minutes_in_seconds=$(( (check_last_block_minutes * 60) - 60 ))
    last_head_block_minutes_in_seconds=$(( (check_last_head_block_minutes * 60) - 60 ))
    if (( ($now_epoch - $last_block_epoch) >= $last_block_minutes_in_seconds )) && (( ($now_epoch - $last_head_block_epoch) <= $last_head_block_minutes_in_seconds )) && (( $configproducerpublickey != $activeproducerpublickey ))
    then
      check_produce_minutes
    fi
  fi
fi

#----------------------------------------------------------------------------------------------------#
# SEND ALERT NOTIFICATIONS TO TELEGRAM BOT (IF THERE'S SOMETHING TO SEND)                            #
#----------------------------------------------------------------------------------------------------#

if $send_message
then
  curl -s -X POST https://api.telegram.org/bot$telegram_token/sendMessage -d chat_id=$telegram_chatid -d text="$telegram_message" &>/dev/null
fi
